baseURL = "https://digital-democracy.netlify.app/"
languageCode = "en-us"
title = "Seminar of digital democracy"
theme = "postyd"


[params]
description = "Exploring the challenges for democracy in the digital age."
author = "Jonathan Piron"
authorWebsite = "https://jonapiron.be"
license = "CC BY-NC-SA 4.0"
licenseTitle = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
favicon = "/favicons/"

  [[params.socialIcon]]
  icon = "fab fa-github"
  title = "github"
  url = "https://github.com/jonapiron/digital-democracy"


[menu]

  [[menu.main]]
  
  [[menu.main]]
  title = "Chapter 1"
  identifier = "ch1"
  weight = "10"
  url = "chapters/01"

  [[menu.main]]
  title = "Chapter 2"
  identifier = "ch2"
  weight = "20"
  url = "chapters/02"

  [[menu.main]]
  title = "Chapter 3"
  identifier = "ch3"
  weight = "30"
  url = "chapters/03"

  [[menu.main]]
  title = "Resources"
  identifier = "resources"
  weight = "40"
  url = "resources"


  [[menu.other]]
  title = "about"
  identifier = "about"
  weight = "10"
  url = "/about"