baseURL = "https://seminarofdigitaldemocracy.net"
languageCode = "en-us"
title = "Seminar of digital democracy"
theme = "postyd"
summarylength = 10
enableEmoji = true

[markup]
[markup.goldmark]
fractions = false

[params]
description = "Exploring the challenges for democracy in the digital age."
author = "Jonathan Piron"
authorWebsite = "https://jonapiron.be"
license = "CC BY-NC-SA 4.0"
licenseTitle = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
favicon = "/favicons/"

  [[params.socialIcon]]
  icon = "fab fa-github"
  title = "github"
  url = "https://github.com/jonapiron/digital-democracy"


[menu]

#  [[menu.main]]
#  title = "Home"
#  identifier = "home"
#  weight = "1"
#  url = "/"

  [[menu.main]]
  title = "Course description"
  identifier = "description"
  weight = "5"
  url = "/course-description"

  [[menu.main]]
  title = "Programme"
  identifier = "programme"
  weight = "10"
  url = "/programme"

  [[menu.main]]
  title = "Sessions"
  identifier = "sessions"
  weight = "15"
  url = "/sessions"
  
  [[menu.main]]
  title = "Tools"
  identifier = "tools"
  weight = "20"
  url = "tools"

  [[menu.main]]
  title = "Resources"
  identifier = "resources"
  weight = "25"
  url = "resources"

  #[[menu.other]]
  #title = "about"
  #identifier = "about"
  #weight = "10"
  #url = "/about"