name = "postyd"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Minimal blog theme built with Bulma CSS"
homepage = "http://example.com/"
tags = ["blog"]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "Jonathan Piron"
  homepage = "https://yelo.studio"